### ISSUE TITLE
Move to maven central?

### ISSUE THREAD

**Issue by ademar111190** [mannodermaus/retrofit-logansquare#23]
jcenter has been shut down, it seems the maven central is the default option to migrate for.

**Comment by mannodermaus** [comment]
I moved the latest release to Maven Central. It will be available at the following coordinates once synchronized: `de.mannodermaus.retrofit2:converter-logansquare:1.4.1`. I have updated the README accordingly, alongside a notice for the archival of this repository.

Thanks for the suggestion!
